### ISSUE TITLE
Thread panic as unbound `clap` dependency picks latest 3.2+ which has behavior change

### ISSUE THREAD

**Issue by cho-m** [gbdev/rgbobj#4]
In Homebrew, we saw a thread panic when testing a rebuild of `rgbds`/`rgbobj` during a `rust` update (https://github.com/Homebrew/homebrew-core/pull/98823)
```
==>/usr/local/Cellar/rgbds/0.5.2/bin/rgbobj -A -s data -p data output.o
  thread 'main' panicked at 'Must use `Arg::allow_invalid_utf8` with `_os` lookups at `[hash: 754F87C87F12EDF4]`', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/clap-3.2.5/src/parser/matches/arg_matches.rs:1732:13
```

The issue appears to be due to changes in newer `clap >= 3.2` (https://github.com/clap-rs/clap/issues/3826). Since the Cargo.toml doesn't specify an upper bound and there is no Cargo.lock, the build picks up newer version (3.2.5) and causes this issue at runtime.

The actual issue for thread panic should probably be fixed, but in mean time, it would be nice to provide a Cargo.lock and/or update Cargo.toml with an upper bound (`3.0.0-beta.2, <3.2`) or fixed (`=3.0.0-beta.2`) restriction to allow reproducible build.

**Comment by ISSOtm** [comment]
I need to update `rgbobj` anyway to support the new RGBDS object format, so I'll also fix that issue while at it.
